### ISSUE TITLE
Add support for retriable 3.0

### ISSUE THREAD

**Issue by kamui** [julik/retriable_proxy#1]
Hey @julik, I'm not sure if you're still maintaining this, but I wanted to let you know I cut a new major version of retriable (3.x). The main breaking change is that a Hash value for `on` not supports matching subclasses. Since this could break existing usage, I decided to cut a major version. Thought I'd let you know.

**Comment by julik** [comment]
Thanks! I willl check if this still works with it

**Comment by julik** [comment]
Seems like nothing is broken and I've released a version with a relaxed version constraint.
